import React, { useState } from 'react';
import { X, Copy, Check, Share2, Sparkles } from 'lucide-react';
import { CopilotMessage } from '../../../types/copilot';

interface ShareModalProps {
  message: CopilotMessage;
  onClose: () => void;
}

export const ShareModal: React.FC<ShareModalProps> = ({ message, onClose }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    const textToCopy = `### IntelliCare AI Copilot Insight\n*Timestamp: ${message.timestamp}*\n\n${message.text}\n\n---\n*Generated by IntelliCare Hospital Operations Copilot*`;
    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/70 backdrop-blur-md animate-in fade-in duration-200">
      <div className="relative w-full max-w-lg rounded-3xl bg-midnight-950/95 border border-cyan-500/30 p-6 shadow-[0_25px_70px_rgba(0,0,0,0.7)] text-slate-100">
        {/* Close Button */}
        <button
          onClick={onClose}
          className="absolute top-4 right-4 p-2 rounded-full bg-surface-100 text-slate-400 hover:text-white transition-colors"
        >
          <X className="w-4 h-4" />
        </button>

        {/* Title */}
        <div className="flex items-center gap-2 mb-4">
          <div className="w-8 h-8 rounded-xl bg-cyan-500/20 border border-cyan-400/40 flex items-center justify-center text-brand-cyan">
            <Share2 className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-white font-display">Share Operational Insight</h3>
            <p className="text-xs text-slate-400">Export or copy this clinical AI response</p>
          </div>
        </div>

        {/* Preview Card */}
        <div className="p-4 rounded-2xl bg-midnight-900 border border-slate-800 text-xs text-slate-300 max-h-64 overflow-y-auto custom-scrollbar mb-5">
          <div className="flex items-center gap-2 mb-2 pb-2 border-b border-slate-800">
            <Sparkles className="w-3.5 h-3.5 text-brand-cyan" />
            <span className="font-bold text-white">IntelliCare Copilot — {message.timestamp}</span>
          </div>
          <div className="whitespace-pre-wrap leading-relaxed">
            {message.text}
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center justify-end gap-3">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl text-xs font-semibold text-slate-400 hover:text-white transition-colors"
          >
            Close
          </button>

          <button
            onClick={handleCopy}
            className="px-5 py-2.5 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-white text-xs font-bold flex items-center gap-2 shadow-[0_0_20px_rgba(22,199,243,0.35)] transition-all"
          >
            {copied ? (
              <>
                <Check className="w-4 h-4 text-emerald-300" />
                <span>Copied to Clipboard!</span>
              </>
            ) : (
              <>
                <Copy className="w-4 h-4" />
                <span>Copy Markdown</span>
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
};
